# Generated by Django 4.1.7 on 2023-04-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=200, null=True, verbose_name='Order id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=200, null=True, verbose_name='Payment id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(max_length=200, null=True, verbose_name='Payment mode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.IntegerField(null=True, verbose_name='Token'),
        ),
    ]
