# Generated by Django 4.1.7 on 2023-05-01 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_name',
            field=models.TextField(null=True, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items'),
        ),
    ]
